### PR TITLE
Improve metrics view

### PR DESCRIPTION
**Pull request by rizo**
Changes:

1. Adds a summary section to graphs (with comparison delta and the last value).
2. Removes table view from master.
3. Improves section rendering.
4. Adds page anchor to metric names in the overview table.

There are probably some questionable CSS bits – suggestions on improvements are welcome! :)

### CODE REVIEW

**Comment by rizo** [comment]
The last commit uses `a` instead of `Link`. @tatchi I noticed that after the recent change you made to `Link` the anchors stopped working. I understand why we want to prevent default event propagation with links, but I wonder what's the best way to use DOM anchors in that case.

Another thing that I noticed is that there's a rerender when the anchor is being jumped to. Any idea how to avoid that, @tatchi?

**Comment by rizo** [comment]
Deployed to: http://autumn.ocamllabs.io/mirage/index

**Comment by tatchi** [comment]
> The last commit uses `a` instead of `Link`. @tatchi I noticed that after the recent change you made to `Link` the anchors stopped working. I understand why we want to prevent default event propagation with links, but I wonder what's the best way to use DOM anchors in that case.
> 
> Another thing that I noticed is that there's a rerender when the anchor is being jumped to. Any idea how to avoid that, @tatchi?

Interesting. It looks like indeed that the jump to anchors does not work when using `ReasonReactRouter.push` function. A workaround might be to add a condition to the `Link` component to verify that the URL does not contain any `#hash`:

```diff
index ee04ff5..569e014 100644
--- a/frontend/src/Components.res
+++ b/frontend/src/Components.res
@@ -917,6 +917,8 @@ module Link = {
 
   @react.component
   let make = (~text=?, ~active=false, ~target=?, ~sx as uSx=[], ~icon=?, ~href) => {
+    let hashPart = href->Js.String2.split("#")->Belt.Array.get(1)
+
     let (text, sx_icon_hover, sx_size) = switch text {
     | Some(text) => (<span> {React.string(text)} </span>, [], sx_medium)
     | None => (React.null, sx_icon_hover, [])
@@ -944,6 +946,7 @@ module Link = {
       onClick={event =>
         // https://github.com/MinimaHQ/safe-routing-blog-app-example/blob/master/02-multiple-types/src/Router.re
         if (
+          Belt.Option.isNone(hashPart) &&
           !(event->ReactEvent.Mouse.defaultPrevented) &&
           (event->ReactEvent.Mouse.button == 0 &&
           (!(event->ReactEvent.Mouse.altKey) &&
```

But as with the currently deployed version, it won't work on a full page refresh since the HTML document is almost empty (react has not built it yet) so the browser has nowhere to scroll to. A possible solution for this could be to create a component that accepts an `id` and when the `url.hash` matches its `id`, scroll to the underlying `div` element he renders:

```reason
@bs.send external scrollIntoView: Dom.element => unit = "scrollIntoView"

module ScrollToSection = {
  @react.component
  let make = (~id, ~children) => {
    let divRef = React.useRef(Js.Nullable.null)
    let url = ReasonReactRouter.useUrl()

    React.useLayoutEffect1(() => {
      if url.hash == id {
        switch divRef.current->Js.Nullable.toOption {
        | None => ()
        | Some(ref) => scrollIntoView(ref)
        }
      }
      None
    }, [url.hash])

    <div id ref={ReactDOM.Ref.domRef(divRef)}> children </div>
  }
}

// USAGE
// If url.hash matches `the-url-hash`, we scroll to this element.
// Works also on full page load
<ScrollToSection id="the-url-hash">...</ScrollToSection>

```

Does that make sense?

**Comment by rizo** [comment]
Hey, @tatchi apologies for the delay. I've been busy with #55 in the last few days.

Do you think we can come back to your suggestion in follow up PRs? I'd like to take some time to understand the trade-offs behind using `#` React links. I don't think the current PR should be blocked by that.

**Comment by tatchi** [comment]
> Hey, @tatchi apologies for the delay. I've been busy with #55 in the last few days.
> 
> Do you think we can come back to your suggestion in follow up PRs? I'd like to take some time to understand the trade-offs behind using `#` React links. I don't think the current PR should be blocked by that.

Yes sure, that's fine 👍

**Pull request merged**
