### PR TITLE
Make log links noticeable by removing log ID from link text

### LINKED ISSUE #291: Make logs link more noticeable
From #285,

>Thanks I didn't notice this link, I think it could be made more noticeable (e.g. using the same style blue+underline for the link, and personally I think that the name of the build "110849-ocluster-build-87cd3f" only adds some "noise" and is not very useful for the end user, the link could just be named "execution logs").

Right now there;s ids in the logs that doesn't help the user figure out that the execution logs is indeed something useful. Perhaps we can add just a `Logs` link and hide the uuids?

### PR DESCRIPTION
**Pull request by punchagan**
Closes #291

### CODE REVIEW

**Comment by art-w** [comment]
Nice! The wording will definitively help, but perhaps part of the confusion is also that we use unstyled black links with no underline? (so it's not obvious what is clickable or not)

**Comment by punchagan** [comment]
On hover, we do change color. So, I feel it may be sufficient with the new wording. 

With external links shown in the primary color, it looks like this.  Does this look alright - I'm not sure? Or do you have any specific ideas on how to display these links? @gs0510 thoughts?

image

**Comment by punchagan** [comment]
Also, I feel we can move the link for Execution logs somewhere else. The other 3 items - last commit, environment and build status are giving information about the current build. The execution logs link is just a link and shouldn't show up along with other "info items", I think.

**Comment by gs0510** [comment]
I agree that we can move the `View Logs` somewhere else. Maybe the status and the `view logs` can be bunched together (and it's more clear that way that one can look at the logs next to the status)? I don't have other ideas at the moment though. :)

**Comment by punchagan** [comment]
What do you think about this? 

image

Older builds with different build and execution logs
image

**Comment by gs0510** [comment]
Looks great imo!

**Comment by punchagan** [comment]
Merging after :+1: from @art-w and @gs0510

**Pull request merged**
